In [1]:
import pandas as pd
import numpy as np
from pandas import DataFrame,Series

In [2]:
from datetime import datetime

In [3]:
t1=datetime(2009,10,20)

In [4]:
t1

datetime.datetime(2009, 10, 20, 0, 0)

In [5]:
type(t1)

datetime.datetime

In [11]:
date_list=[datetime(2009,1,20),
           datetime(2009,2,20),
           datetime(2010,3,20),
           datetime(2009,2,10),
           datetime(2009,10,20)
          ]

In [7]:
date_list

[datetime.datetime(2009, 1, 20, 0, 0),
 datetime.datetime(2009, 2, 20, 0, 0),
 datetime.datetime(2010, 3, 20, 0, 0),
 datetime.datetime(2009, 2, 10, 0, 0),
 datetime.datetime(2009, 10, 20, 0, 0)]

In [8]:
s1 = Series(np.random.rand(5),index=date_list)

In [9]:
s1

2009-01-20    0.507284
2009-02-20    0.467590
2010-03-20    0.023946
2009-02-10    0.357565
2009-10-20    0.953846
dtype: float64

In [12]:
s1.index

DatetimeIndex(['2009-01-20', '2009-02-20', '2010-03-20', '2009-02-10',
               '2009-10-20'],
              dtype='datetime64[ns]', freq=None)

In [13]:
s1[1]

0.46759011011821083

In [14]:
s1['2009-01-20']

2009-01-20    0.507284
dtype: float64

In [15]:
s1[datetime(2009,1,20)]

0.5072841290706184

In [16]:
s1['20090120']

2009-01-20    0.507284
dtype: float64

In [17]:
s1['2009-02']

2009-02-20    0.467590
2009-02-10    0.357565
dtype: float64

In [19]:
s1['2009-2']

2009-02-20    0.467590
2009-02-10    0.357565
dtype: float64

In [22]:
#pd内部提供函数
pd.date_range(start='2009-01-01',periods=100)

DatetimeIndex(['2009-01-01', '2009-01-02', '2009-01-03', '2009-01-04',
               '2009-01-05', '2009-01-06', '2009-01-07', '2009-01-08',
               '2009-01-09', '2009-01-10', '2009-01-11', '2009-01-12',
               '2009-01-13', '2009-01-14', '2009-01-15', '2009-01-16',
               '2009-01-17', '2009-01-18', '2009-01-19', '2009-01-20',
               '2009-01-21', '2009-01-22', '2009-01-23', '2009-01-24',
               '2009-01-25', '2009-01-26', '2009-01-27', '2009-01-28',
               '2009-01-29', '2009-01-30', '2009-01-31', '2009-02-01',
               '2009-02-02', '2009-02-03', '2009-02-04', '2009-02-05',
               '2009-02-06', '2009-02-07', '2009-02-08', '2009-02-09',
               '2009-02-10', '2009-02-11', '2009-02-12', '2009-02-13',
               '2009-02-14', '2009-02-15', '2009-02-16', '2009-02-17',
               '2009-02-18', '2009-02-19', '2009-02-20', '2009-02-21',
               '2009-02-22', '2009-02-23', '2009-02-24', '2009-02-25',
               '2009-02-26', '2009-02-27', '2009-02-28', '2009-03-01',
               '2009-03-02', '2009-03-03', '2009-03-04', '2009-03-05',
               '2009-03-06', '2009-03-07', '2009-03-08', '2009-03-09',
               '2009-03-10', '2009-03-11', '2009-03-12', '2009-03-13',
               '2009-03-14', '2009-03-15', '2009-03-16', '2009-03-17',
               '2009-03-18', '2009-03-19', '2009-03-20', '2009-03-21',
               '2009-03-22', '2009-03-23', '2009-03-24', '2009-03-25',
               '2009-03-26', '2009-03-27', '2009-03-28', '2009-03-29',
               '2009-03-30', '2009-03-31', '2009-04-01', '2009-04-02',
               '2009-04-03', '2009-04-04', '2009-04-05', '2009-04-06',
               '2009-04-07', '2009-04-08', '2009-04-09', '2009-04-10'],
              dtype='datetime64[ns]', freq='D')

In [23]:
pd.date_range(start='2009-01-01',periods=100,freq='W')

DatetimeIndex(['2009-01-04', '2009-01-11', '2009-01-18', '2009-01-25',
               '2009-02-01', '2009-02-08', '2009-02-15', '2009-02-22',
               '2009-03-01', '2009-03-08', '2009-03-15', '2009-03-22',
               '2009-03-29', '2009-04-05', '2009-04-12', '2009-04-19',
               '2009-04-26', '2009-05-03', '2009-05-10', '2009-05-17',
               '2009-05-24', '2009-05-31', '2009-06-07', '2009-06-14',
               '2009-06-21', '2009-06-28', '2009-07-05', '2009-07-12',
               '2009-07-19', '2009-07-26', '2009-08-02', '2009-08-09',
               '2009-08-16', '2009-08-23', '2009-08-30', '2009-09-06',
               '2009-09-13', '2009-09-20', '2009-09-27', '2009-10-04',
               '2009-10-11', '2009-10-18', '2009-10-25', '2009-11-01',
               '2009-11-08', '2009-11-15', '2009-11-22', '2009-11-29',
               '2009-12-06', '2009-12-13', '2009-12-20', '2009-12-27',
               '2010-01-03', '2010-01-10', '2010-01-17', '2010-01-24',
               '2010-01-31', '2010-02-07', '2010-02-14', '2010-02-21',
               '2010-02-28', '2010-03-07', '2010-03-14', '2010-03-21',
               '2010-03-28', '2010-04-04', '2010-04-11', '2010-04-18',
               '2010-04-25', '2010-05-02', '2010-05-09', '2010-05-16',
               '2010-05-23', '2010-05-30', '2010-06-06', '2010-06-13',
               '2010-06-20', '2010-06-27', '2010-07-04', '2010-07-11',
               '2010-07-18', '2010-07-25', '2010-08-01', '2010-08-08',
               '2010-08-15', '2010-08-22', '2010-08-29', '2010-09-05',
               '2010-09-12', '2010-09-19', '2010-09-26', '2010-10-03',
               '2010-10-10', '2010-10-17', '2010-10-24', '2010-10-31',
               '2010-11-07', '2010-11-14', '2010-11-21', '2010-11-28'],
              dtype='datetime64[ns]', freq='W-SUN')

In [24]:
pd.date_range(start='2009-01-01',periods=100,freq='W-MON')

DatetimeIndex(['2009-01-05', '2009-01-12', '2009-01-19', '2009-01-26',
               '2009-02-02', '2009-02-09', '2009-02-16', '2009-02-23',
               '2009-03-02', '2009-03-09', '2009-03-16', '2009-03-23',
               '2009-03-30', '2009-04-06', '2009-04-13', '2009-04-20',
               '2009-04-27', '2009-05-04', '2009-05-11', '2009-05-18',
               '2009-05-25', '2009-06-01', '2009-06-08', '2009-06-15',
               '2009-06-22', '2009-06-29', '2009-07-06', '2009-07-13',
               '2009-07-20', '2009-07-27', '2009-08-03', '2009-08-10',
               '2009-08-17', '2009-08-24', '2009-08-31', '2009-09-07',
               '2009-09-14', '2009-09-21', '2009-09-28', '2009-10-05',
               '2009-10-12', '2009-10-19', '2009-10-26', '2009-11-02',
               '2009-11-09', '2009-11-16', '2009-11-23', '2009-11-30',
               '2009-12-07', '2009-12-14', '2009-12-21', '2009-12-28',
               '2010-01-04', '2010-01-11', '2010-01-18', '2010-01-25',
               '2010-02-01', '2010-02-08', '2010-02-15', '2010-02-22',
               '2010-03-01', '2010-03-08', '2010-03-15', '2010-03-22',
               '2010-03-29', '2010-04-05', '2010-04-12', '2010-04-19',
               '2010-04-26', '2010-05-03', '2010-05-10', '2010-05-17',
               '2010-05-24', '2010-05-31', '2010-06-07', '2010-06-14',
               '2010-06-21', '2010-06-28', '2010-07-05', '2010-07-12',
               '2010-07-19', '2010-07-26', '2010-08-02', '2010-08-09',
               '2010-08-16', '2010-08-23', '2010-08-30', '2010-09-06',
               '2010-09-13', '2010-09-20', '2010-09-27', '2010-10-04',
               '2010-10-11', '2010-10-18', '2010-10-25', '2010-11-01',
               '2010-11-08', '2010-11-15', '2010-11-22', '2010-11-29'],
              dtype='datetime64[ns]', freq='W-MON')

In [25]:
pd.date_range(start='2009-01-01',periods=100,freq='H')

DatetimeIndex(['2009-01-01 00:00:00', '2009-01-01 01:00:00',
               '2009-01-01 02:00:00', '2009-01-01 03:00:00',
               '2009-01-01 04:00:00', '2009-01-01 05:00:00',
               '2009-01-01 06:00:00', '2009-01-01 07:00:00',
               '2009-01-01 08:00:00', '2009-01-01 09:00:00',
               '2009-01-01 10:00:00', '2009-01-01 11:00:00',
               '2009-01-01 12:00:00', '2009-01-01 13:00:00',
               '2009-01-01 14:00:00', '2009-01-01 15:00:00',
               '2009-01-01 16:00:00', '2009-01-01 17:00:00',
               '2009-01-01 18:00:00', '2009-01-01 19:00:00',
               '2009-01-01 20:00:00', '2009-01-01 21:00:00',
               '2009-01-01 22:00:00', '2009-01-01 23:00:00',
               '2009-01-02 00:00:00', '2009-01-02 01:00:00',
               '2009-01-02 02:00:00', '2009-01-02 03:00:00',
               '2009-01-02 04:00:00', '2009-01-02 05:00:00',
               '2009-01-02 06:00:00', '2009-01-02 07:00:00',
               '2009-01-02 08:00:00', '2009-01-02 09:00:00',
               '2009-01-02 10:00:00', '2009-01-02 11:00:00',
               '2009-01-02 12:00:00', '2009-01-02 13:00:00',
               '2009-01-02 14:00:00', '2009-01-02 15:00:00',
               '2009-01-02 16:00:00', '2009-01-02 17:00:00',
               '2009-01-02 18:00:00', '2009-01-02 19:00:00',
               '2009-01-02 20:00:00', '2009-01-02 21:00:00',
               '2009-01-02 22:00:00', '2009-01-02 23:00:00',
               '2009-01-03 00:00:00', '2009-01-03 01:00:00',
               '2009-01-03 02:00:00', '2009-01-03 03:00:00',
               '2009-01-03 04:00:00', '2009-01-03 05:00:00',
               '2009-01-03 06:00:00', '2009-01-03 07:00:00',
               '2009-01-03 08:00:00', '2009-01-03 09:00:00',
               '2009-01-03 10:00:00', '2009-01-03 11:00:00',
               '2009-01-03 12:00:00', '2009-01-03 13:00:00',
               '2009-01-03 14:00:00', '2009-01-03 15:00:00',
               '2009-01-03 16:00:00', '2009-01-03 17:00:00',
               '2009-01-03 18:00:00', '2009-01-03 19:00:00',
               '2009-01-03 20:00:00', '2009-01-03 21:00:00',
               '2009-01-03 22:00:00', '2009-01-03 23:00:00',
               '2009-01-04 00:00:00', '2009-01-04 01:00:00',
               '2009-01-04 02:00:00', '2009-01-04 03:00:00',
               '2009-01-04 04:00:00', '2009-01-04 05:00:00',
               '2009-01-04 06:00:00', '2009-01-04 07:00:00',
               '2009-01-04 08:00:00', '2009-01-04 09:00:00',
               '2009-01-04 10:00:00', '2009-01-04 11:00:00',
               '2009-01-04 12:00:00', '2009-01-04 13:00:00',
               '2009-01-04 14:00:00', '2009-01-04 15:00:00',
               '2009-01-04 16:00:00', '2009-01-04 17:00:00',
               '2009-01-04 18:00:00', '2009-01-04 19:00:00',
               '2009-01-04 20:00:00', '2009-01-04 21:00:00',
               '2009-01-04 22:00:00', '2009-01-04 23:00:00',
               '2009-01-05 00:00:00', '2009-01-05 01:00:00',
               '2009-01-05 02:00:00', '2009-01-05 03:00:00'],
              dtype='datetime64[ns]', freq='H')